project_id = "hcsnyrbkrydmopnojufj"

[functions.ai-music-chat]
verify_jwt = false

[functions.youtube-search]
verify_jwt = false

[functions.autoplay-recommend]
verify_jwt = false

[functions.top-charts]
verify_jwt = false
